CREATE TABLE IF NOT EXISTS tenants (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entity_id` CHAR(32) NOT NULL UNIQUE,
  `name` VARCHAR(64) NOT NULL,
  `secret_key` VARCHAR(32) NOT NULL,
  `profile_photo` VARCHAR(384),
  `cover_photo` VARCHAR(384),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `archived_at` TIMESTAMP NULL,
  PRIMARY KEY (id)
);