CREATE TABLE IF NOT EXISTS packages (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entity_id` CHAR(32) NOT NULL UNIQUE,
  `name` VARCHAR(32) NOT NULL,
  `is_active` BOOLEAN NOT NULL,
  `is_default` BOOLEAN NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `archived_at` TIMESTAMP NULL,
  PRIMARY KEY (id)
);