/**
 * This file is auto-generated by executing "npm run container:build"
 * If you update this file, it will be overwritten.
 * @since 2025-06-01T13:52:26.966Z
 */
import { AppAuthController } from "./core/auth/controllers/app-auth.controller";
import { AppAuthService } from "./core/auth/services/app-auth-service";
import { NativeRBACService } from "./core/providers/authorization/rbac/rbac.service";
import { RedisCacheService } from "./core/providers/cache/redis/redis.service";
import { FirestoreHelper } from "./core/providers/database/firestore/firestore.helper";
import { FirestoreService } from "./core/providers/database/firestore/firestore.service";
import { JsonWebToken } from "./core/providers/jwt/jsonwebtoken/json-web-token.service";
import { RequesterIdentityFactory } from "./core/requester/requester-identity.factory";
import { RequesterIdentityMiddleware } from "./core/requester/requester-identity.middleware";
import { RequesterTokenService } from "./core/requester/requester-token.service";
import { ProxyRouter } from "./core/router/proxy-router";
import { AmazonS3Service } from "./core/services/aws/s3/aws3.service";
import { EntityCertifier } from "./core/services/entity-certifier/entity-certifier.service";
import { FirebaseEnvBasedProjectService } from "./core/services/firebase/firebase-env-based-project.service";
import { PermissionTokenValidator } from "./core/services/rbac/permission-token.validator";
import { PermissionManager } from "./core/services/rbac/permissions.manager";
import { Application } from "./core/application";

Application.container().bind(AppAuthController).toSelf();
Application.container().bind(AppAuthService).toSelf();
Application.container().bind(NativeRBACService).toSelf();
Application.container().bind(RedisCacheService).toSelf();
Application.container().bind(FirestoreHelper).toSelf();
Application.container().bind(FirestoreService).toSelf();
Application.container().bind(JsonWebToken).toSelf();
Application.container().bind(RequesterIdentityFactory).toSelf();
Application.container().bind(RequesterIdentityMiddleware).toSelf();
Application.container().bind(RequesterTokenService).toSelf();
Application.container().bind(ProxyRouter).toSelf();
Application.container().bind(AmazonS3Service).toSelf();
Application.container().bind(EntityCertifier).toSelf();
Application.container().bind(FirebaseEnvBasedProjectService).toSelf();
Application.container().bind(PermissionTokenValidator).toSelf();
Application.container().bind(PermissionManager).toSelf();
