/**
 * This file is auto-generated by executing "bin/app container:build"
 * If you update this file, it will be overwritten.
 * @since 2025-05-30T20:56:08.649Z
 */
import { NativeRBACService } from "../src/core/providers/authorization/rbac/rbac.service";
import { JsonWebToken } from "../src/core/providers/jwt/jsonwebtoken/json-web-token.service";
import { RequesterIdentityFactory } from "../src/core/requester/requester-identity.factory";
import { RequesterIdentityMiddleware } from "../src/core/requester/requester-identity.middleware";
import { RequesterTokenService } from "../src/core/requester/requester-token.service";
import { PermissionTokenValidator } from "../src/core/services/rbac/permission-token.validator";
import { PermissionManager } from "../src/core/services/rbac/permissions.manager";
import { Application } from "./core/application";

Application.container().bind(NativeRBACService).toSelf();
Application.container().bind(JsonWebToken).toSelf();
Application.container().bind(RequesterIdentityFactory).toSelf();
Application.container().bind(RequesterIdentityMiddleware).toSelf();
Application.container().bind(RequesterTokenService).toSelf();
Application.container().bind(PermissionTokenValidator).toSelf();
Application.container().bind(PermissionManager).toSelf();
