/**
 * This file is auto-generated by executing "npm run container:build"
 * If you update this file, it will be overwritten.
 * @since 2025-05-31T07:29:56.654Z
 */
import { NativeRBACService } from "./core/providers/authorization/rbac/rbac.service";
import { JsonWebToken } from "./core/providers/jwt/jsonwebtoken/json-web-token.service";
import { RequesterIdentityFactory } from "./core/requester/requester-identity.factory";
import { RequesterIdentityMiddleware } from "./core/requester/requester-identity.middleware";
import { RequesterTokenService } from "./core/requester/requester-token.service";
import { ProxyRouter } from "./core/router/proxy-router";
import { PermissionTokenValidator } from "./core/services/rbac/permission-token.validator";
import { PermissionManager } from "./core/services/rbac/permissions.manager";
import { Application } from "./core/application";

Application.container().bind(NativeRBACService).toSelf();
Application.container().bind(JsonWebToken).toSelf();
Application.container().bind(RequesterIdentityFactory).toSelf();
Application.container().bind(RequesterIdentityMiddleware).toSelf();
Application.container().bind(RequesterTokenService).toSelf();
Application.container().bind(ProxyRouter).toSelf();
Application.container().bind(PermissionTokenValidator).toSelf();
Application.container().bind(PermissionManager).toSelf();
